import React,{useEffect,useMemo,useState} from 'react';
import {evaluateGraph,demoPrediction} from './graphEvaluation.js';
import './evaluation.css';
const colors={correct:'#15956c',wrong_type:'#d38a00',missing:'#d43b51',extra:'#8257d8',excluded:'#788696'};
const labels={correct:'Correct',wrong_type:'Wrong type',missing:'Missing',extra:'Extra',excluded:'Excluded / unknown'};
const pct=x=>x==null?'—':`${(x*100).toFixed(1)}%`;
const download=(data,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
function Overlay({report,side,image,filter,focused,onFocus,boxes}){
 const graph=report[side],nodeErrors=report.nodeErrors,edgeErrors=report.edgeErrors;
 const status=(item,kind)=>{const list=kind==='node'?nodeErrors:edgeErrors;const i=list.findIndex(e=>e[side]===item);if(i>=0)return {kind:list[i].kind,key:`${kind}-${i}`};if(kind==='edge'&&report.excluded.some(e=>e[side]===item))return {kind:'excluded'};return {kind:'correct'};};
 const visible=s=>filter==='all'||s.kind===filter||filter==='errors'&&s.kind!=='correct';
 const width=image.width||1000,height=image.height||1000;
 return <div className="ev-view"><h3>{side==='gold'?'Manual reference':'Prediction'}</h3><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${side} graph comparison`}>
 <image href={image.url} width={width} height={height} opacity=".65"/>
 {graph.edges.map((e,i)=>{const a=graph.nodes.find(n=>n.id===e.a),b=graph.nodes.find(n=>n.id===e.b),s=status(e,'edge');if(!visible(s))return null;return <g key={i} onClick={()=>onFocus(s.key)} style={{cursor:'pointer'}}><title>{`${a.label||a.type} ↔ ${b.label||b.type}: ${e.relation} (${labels[s.kind]})`}</title><line x1={a.x*width} y1={a.y*height} x2={b.x*width} y2={b.y*height} stroke={colors[s.kind]} strokeWidth={focused===s.key?7:3} vectorEffect="non-scaling-stroke" strokeDasharray={e.relation==='open_connected'?'9 6':e.relation==='adjacent_to'?'2 6':e.relation==='uncertain'?'9 4 2 4':undefined}/><line x1={a.x*width} y1={a.y*height} x2={b.x*width} y2={b.y*height} stroke="transparent" strokeWidth="14" vectorEffect="non-scaling-stroke"/></g>;})}
 {graph.nodes.map(n=>{const s=status(n,'node');if(!visible(s))return null;const b=n.bbox_xyxy;return <g key={n.id} onClick={()=>onFocus(s.key)} style={{cursor:'pointer'}}><title>{`${n.label||n.id}: ${n.type} (${labels[s.kind]})`}</title>{boxes&&<rect x={b[0]*width} y={b[1]*height} width={(b[2]-b[0])*width} height={(b[3]-b[1])*height} fill={colors[s.kind]} fillOpacity=".07" stroke={colors[s.kind]} strokeWidth={focused===s.key?4:1} vectorEffect="non-scaling-stroke"/>}<circle cx={n.x*width} cy={n.y*height} r={Math.max(width,height)*.009} fill={colors[s.kind]} stroke="white" strokeWidth="2"/><text x={n.x*width} y={n.y*height-Math.max(width,height)*.014} textAnchor="middle" fontSize={Math.max(width,height)*.016} fill="#14213a" stroke="white" strokeWidth="3" paintOrder="stroke">{n.type}</text></g>;})}
 </svg></div>;
}
export default function EvaluationDashboard(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[planId,setPlanId]=useState(''),[method,setMethod]=useState('reference'),[uploaded,setUploaded]=useState({}),[filter,setFilter]=useState('all'),[focused,setFocused]=useState(null),[boxes,setBoxes]=useState(false),[completePairs,setCompletePairs]=useState(false);
 async function refresh(){try{const response=await fetch('/api/evaluation/benchmark');const d=await response.json();if(!response.ok)throw Error(d.error);setData(d);setPlanId(id=>id||d.plans[0]?.annotation.plan_id||'');setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{refresh();},[]);
 const entry=data?.plans.find(p=>p.annotation.plan_id===planId),reference=entry?.annotation;
 const predictions=method==='uploaded'?uploaded:data?.methods[method];
 const computed=useMemo(()=>{if(!reference)return {};if(entry.imageError)return {problem:entry.imageError};if(method==='reference')return {};const pred=method==='demo'?demoPrediction(reference):predictions?.[planId];if(!pred)return {problem:'No prediction for this plan. Missing runs must be reported as missing, not scored as perfect.'};try{return {report:evaluateGraph(reference,pred,{completePairs})};}catch(e){return {problem:e.message};}},[reference,method,predictions,planId,completePairs]);
 const report=computed.report;
 async function upload(event){try{const next={};for(const file of event.target.files){const text=await file.text();const records=file.name.endsWith('.jsonl')?text.split(/\r?\n/).filter(s=>s.trim()).map(s=>JSON.parse(s)):[JSON.parse(text)];for(const record of records){const id=record.plan_id;if(!id)throw Error(`${file.name}: plan_id required`);if(next[id])throw Error(`Duplicate plan ${id}`);next[id]=record;}}setUploaded(next);setMethod('uploaded');setError('');}catch(e){setError(e.message);}event.target.value='';}
 const errors=report?[...report.nodeErrors.map((e,i)=>({...e,entity:'Room',key:`node-${i}`})),...report.edgeErrors.map((e,i)=>({...e,entity:'Edge',key:`edge-${i}`}))]:[];
 const name=(g,id)=>{const n=g.nodes.find(n=>n.id===id);return n?.label||n?.type||id;};
 const describe=e=>e.entity==='Room'?`${e.gold?.label||e.pred?.label||e.gold?.id||e.pred?.id}: ${e.gold?.type||'∅'} → ${e.pred?.type||'∅'}`:`${e.gold?`${name(report.gold,e.gold.a)} ↔ ${name(report.gold,e.gold.b)}`:`${name(report.pred,e.pred.a)} ↔ ${name(report.pred,e.pred.b)}`}: ${e.gold?.relation||'∅'} → ${e.pred?.relation||'∅'}`;
 return <main className="evaluation"><header><div><p>FLOORPLAN BENCHMARK</p><h1>Graph evaluation</h1><span>Compare extraction results against your saved manual annotations.</span></div><a href="/" target="_blank" rel="noreferrer">Open annotation tool ↗</a></header>
 {error&&<p role="alert" className="ev-alert">{error}</p>}
 <section className="ev-controls"><label>Floorplan<select value={planId} onChange={e=>{setPlanId(e.target.value);setFocused(null);}}>{data?.plans.map(p=><option key={p.annotation.plan_id}>{p.annotation.plan_id}</option>)}</select></label><label>Method<select value={method} onChange={e=>{setMethod(e.target.value);setFocused(null);}}><option value="reference">Reference only — no model selected</option><option value="demo">Synthetic demo — not model results</option>{Object.keys(data?.methods||{}).map(m=><option key={m}>{m}</option>)}{Object.keys(uploaded).length>0&&<option value="uploaded">Uploaded predictions</option>}</select></label><label className="ev-upload">Load prediction JSON / JSONL<input type="file" multiple accept=".json,.jsonl" onChange={upload}/></label><button onClick={refresh}>Refresh files</button>{report&&<button onClick={()=>download(report,`${planId}.${method}.evaluation.json`)}>Download comparison</button>}</section>
 <p>{data?.plans.length||0} saved references · Matching: class-blind box IoU ≥ 0.30 · One-to-one spatial assignment · Threshold is provisional until calibrated.</p>
 <label className="ev-option"><input type="checkbox" checked={completePairs} onChange={e=>setCompletePairs(e.target.checked)}/> Treat all completed annotations as exhaustive: an unlisted pair means no direct relation. This affects scoring only; reference files are unchanged.</label>
 {method==='demo'&&<p className="ev-demo">SYNTHETIC DEMO — deliberately changed labels and removed rooms/edges. These are not model predictions.</p>}
 {computed.problem&&<p className="ev-alert">{computed.problem}</p>}
 {reference&&method==='reference'&&<section className="ev-empty"><h2>References are ready</h2><p>{reference.nodes.length} rooms · {reference.edges.length} edges in {planId}. Choose the synthetic demo to explore error highlighting, or load predictions to evaluate a model.</p><p>Save model outputs in <code>cubicasa_eval/predictions/&lt;method&gt;/&lt;plan_id&gt;.json</code>, then refresh. Missing predictions are kept visible.</p><img src={`/api/evaluation/image?name=${encodeURIComponent(entry.imageName)}`} alt="Selected reference floorplan"/></section>}
 {report&&<><div className="ev-stats">{[['Node detection F1',pct(report.node_metrics.f1)],['Matched room type accuracy',pct(report.type_accuracy)],['Typed edge F1',pct(report.edge_metrics.f1)],['Aligned edit cost',report.aligned_edit_cost],['Excluded pairs',report.excluded.length]].map(([k,v])=><div key={k}><strong>{v}</strong><span>{k}</span></div>)}</div>
 {report.warnings.map(w=><p className="ev-demo" key={w}>{w}</p>)}
 <div className="ev-legend">{Object.entries(labels).map(([k,v])=><button aria-pressed={filter===k} key={k} onClick={()=>setFilter(k)}><i style={{background:colors[k]}}/>{v}</button>)}<button onClick={()=>setFilter('all')}>Show all</button><button onClick={()=>setFilter('errors')}>Errors only</button><label><input type="checkbox" checked={boxes} onChange={e=>setBoxes(e.target.checked)}/> Room boxes</label></div>
 <p>Colour = evaluation result. Line pattern = relation: solid door, dashed open passage, dotted shared wall. Click an error below to highlight it.</p>
 <div className="ev-canvases">{['gold','pred'].map(side=><Overlay key={side} report={report} side={side} image={{...reference.image,url:`/api/evaluation/image?name=${encodeURIComponent(entry.imageName)}`}} filter={filter} focused={focused} onFocus={setFocused} boxes={boxes}/>)}</div>
 <section className="ev-results"><h2>Differences <small>({errors.length})</small></h2><p>Reference → prediction. Edge scoring includes unmatched-room edges; edit cost excludes those incident edges to avoid double counting.</p>{errors.length===0?<p>No differences under the current matching and coverage rules.</p>:errors.map(e=><button className={`ev-error ${focused===e.key?'selected':''}`} key={e.key} onClick={()=>{setFocused(e.key);setFilter('all');setBoxes(true);}}><strong style={{color:colors[e.kind]}}>{e.entity} · {labels[e.kind]}</strong><span>{describe(e)}</span></button>)}
 <details><summary>Spatial correspondences ({report.matches.length}) — inspect before freezing evaluation</summary>{report.matches.map(m=><p key={m.pred_id}>{name(report.pred,m.pred_id)} → {name(report.gold,m.gold_id)} · IoU {m.iou.toFixed(3)} · {m.pred_id} → {m.gold_id}</p>)}</details>
 <details><summary>Per-relation metrics and exclusions</summary><pre>{JSON.stringify({per_relation:report.per_relation,excluded:report.excluded},null,2)}</pre></details></section></>}
 </main>;
}
