import React, {useEffect, useRef, useState} from 'react';
import './manual.css';
import {SCHEMA, polygonError, contains, withPolygon, exportGraph} from './roomGeometry.js';
const TYPES = ['LivingRoom','Bedroom','Kitchen','Dining','Bath','Storage','Entry','Corridor','Garage','Outdoor','Other'];
const RELATIONS = {connected_by_door:'Door', open_connected:'Open passage', adjacent_to:'Shared wall only', uncertain:'Uncertain'};
const COLOURS = {connected_by_door:'#a21caf',open_connected:'#059669',adjacent_to:'#2563eb',uncertain:'#d97706'};
const pairKey = (a,b) => JSON.stringify([a,b].sort());
const blank = () => ({schema_version:SCHEMA,plan_id:'',reviewer:'',status:'draft',provenance:'manual_from_raster',notes:'',image:null,nodes:[],edges:[],all_pairs_reviewed:false});
function validate(d) {
  if(!['floorplan-manual-graph/1',SCHEMA].includes(d?.schema_version) || !Array.isArray(d.nodes) || !Array.isArray(d.edges) || typeof d.plan_id !== 'string' || typeof d.reviewer !== 'string' || typeof d.notes !== 'string') throw Error('Not a supported manual graph JSON.');
  if(!d.image || typeof d.image.name !== 'string' || !Number.isFinite(d.image.width) || !Number.isFinite(d.image.height) || d.image.width<=0 || d.image.height<=0 || !/^[a-f0-9]{64}$/.test(d.image.sha256)) throw Error('Missing image identity.');
  const ids = new Set();
  for(const n of d.nodes) {if(typeof n.id !== 'string' || ids.has(n.id) || !TYPES.includes(n.type) || typeof n.label !== 'string' || !Number.isFinite(n.x) || !Number.isFinite(n.y) || n.x<0 || n.x>1 || n.y<0 || n.y>1) throw Error('Invalid or duplicate room node.'); ids.add(n.id);}
  const pairs=new Set();
  for(const e of d.edges) {const key=pairKey(e.a,e.b); if(!ids.has(e.a)||!ids.has(e.b)||e.a===e.b||!Object.hasOwn(RELATIONS,e.relation)||pairs.has(key)) throw Error('Invalid or duplicate edge.'); pairs.add(key);}
  return exportGraph(d);
}
export default function ManualAnnotator() {
  const [doc,setDoc]=useState(blank),[image,setImage]=useState(null),[selected,setSelected]=useState(null),[mode,setMode]=useState('add'),[kind,setKind]=useState('Bedroom'),[relation,setRelation]=useState('connected_by_door'),[pending,setPending]=useState(null),[message,setMessage]=useState(''),[zoom,setZoom]=useState(1),[history,setHistory]=useState([]);
  const [outline,setOutline]=useState(null),[outlineTarget,setOutlineTarget]=useState(null),[showBoxes,setShowBoxes]=useState(true);
  const [diskStatus,setDiskStatus]=useState('Upload an image to enable folder autosave.');
  const storage=useRef(null),saveQueue=useRef(Promise.resolve());
  const svg=useRef(),drag=useRef(null),imageRef=useRef(null),docRef=useRef(doc),fileRef=useRef(),[cache,setCache]=useState(false);
  docRef.current=doc;
  useEffect(()=>{try{setCache(!!localStorage.getItem('fyp-manual-draft-v1'));}catch{} return ()=>{if(imageRef.current) URL.revokeObjectURL(imageRef.current);};},[]);
  useEffect(()=>{if(!doc.image)return; try{localStorage.setItem('fyp-manual-draft-v1',JSON.stringify(exportGraph(doc)));setCache(true);}catch{setMessage('Browser autosave unavailable. Download JSON to keep your work.');}},[doc]);
  useEffect(()=>{const warn=e=>{if(docRef.current.image){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
  useEffect(()=>{
    const target=storage.current;if(!target||!doc.image||target.sha256!==doc.image.sha256)return;
    setDiskStatus('Saving to cubicasa_eval…');
    const annotation=exportGraph(doc);
    const timer=setTimeout(()=>{saveQueue.current=saveQueue.current.catch(()=>{}).then(async()=>{
      try{if(target.blocked)return;const response=await fetch('/api/local-plan/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:target.key,revision:target.revision,annotation})});const result=await response.json();if(!response.ok){if(response.status===409)target.blocked=true;throw Error(result.error||'Save failed.');}target.revision=result.revision;if(storage.current===target&&docRef.current===doc)setDiskStatus(`Saved automatically: ${result.annotation_path}`);
      }catch(e){if(storage.current===target)setDiskStatus(`Not saved to folder: ${e.message} Use Download JSON as backup.`);}
    });},500);
    return ()=>clearTimeout(timer);
  },[doc]);
  const change = fn => {setHistory(h=>[...h.slice(-49),doc]);setDoc(d=>({...fn(d),status:'draft',all_pairs_reviewed:false}));};
  const replace = d => {storage.current=null;setDiskStatus('Select the original image to enable folder autosave.');setOutline(null);setOutlineTarget(null);setHistory([]);setDoc(d);setSelected(null);setPending(null);setMode('add');setZoom(1);if(imageRef.current)URL.revokeObjectURL(imageRef.current);imageRef.current=null;setImage(null);};
  const loadImage=async f=>{if(!f)return;try{
    const bytes=await f.arrayBuffer();const sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
    if(doc.image && doc.image.sha256!==sha256)throw Error('This image differs from the current annotation. Download your JSON, then choose New plan first.');
    const url=URL.createObjectURL(f),im=new Image(); await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=()=>reject(Error('Cannot read this image.'));im.src=url;});
    if(imageRef.current)URL.revokeObjectURL(imageRef.current);imageRef.current=url;setImage(url);
    const response=await fetch('/api/local-plan/upload?name='+encodeURIComponent(f.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:bytes});
    const saved=await response.json();if(!response.ok)throw Error(saved.error||'Could not store image.');
    storage.current={...saved,blocked:false};
    const restored=saved.annotation?validate(saved.annotation):null;
    if(restored&&doc.image&&(doc.nodes.length||doc.edges.length)){storage.current=null;throw Error('This image already has saved annotations. Start a new plan and upload it to reopen them; your current draft has been kept.');}
    setDoc(d=>restored||({...d,plan_id:d.plan_id||saved.plan_id,source_dir:saved.source_dir,image:{name:f.name,width:im.naturalWidth,height:im.naturalHeight,sha256,local_path:saved.image_path}}));
    setMessage(restored?'Saved annotation reopened with its image.':`Image copied to ${saved.image_path}. Graph edits now autosave to the matching annotation file.`);
  }catch(e){setMessage(e.message);} };
  const point=e=>{const p=svg.current.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.current.getScreenCTM().inverse());return {x:Math.max(0,Math.min(1,q.x/doc.image.width)),y:Math.max(0,Math.min(1,q.y/doc.image.height))};};
  const nodeClick=(e,n)=>{e.stopPropagation();setSelected(n.id);if(mode==='connect'){if(!pending){setPending(n.id);return;}if(pending===n.id){setPending(null);return;}change(d=>({...d,edges:[...d.edges.filter(x=>pairKey(x.a,x.b)!==pairKey(pending,n.id)),{a:pending,b:n.id,relation}]}));setPending(null);}};
  const save=()=>{const data={...exportGraph(doc),updated_at:new Date().toISOString()};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${doc.plan_id.replace(/[^a-zA-Z0-9_-]/g,'_')||'plan'}.graph.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('JSON downloaded. Keep it alongside the original image.');};
  const startOutline = target => {setOutline([]);setOutlineTarget(target);setMode('outline');setPending(null);setMessage('Click each room corner in order, then Finish outline. The last edge closes automatically.');};
  const cancelOutline = () => {setOutline(null);setOutlineTarget(null);setMode('move');};
  const finishOutline = () => {const error=polygonError(outline);if(error){setMessage(error);return;}
    const id=outlineTarget||crypto.randomUUID();
    change(d=>{const base=d.nodes.find(n=>n.id===id)||{id,type:kind,label:`${kind} ${d.nodes.filter(n=>n.type===kind).length+1}`,x:-1,y:-1};const room=withPolygon(base,outline);return {...d,nodes:outlineTarget?d.nodes.map(n=>n.id===id?room:n):[...d.nodes,room]};});
    setSelected(id);cancelOutline();setMessage('Outline saved; its enclosing box is derived automatically. Drag the white corners to refine it.');
  };
  const editVertex = (index,remove=false) => {if(!active?.polygon)return;const points=[...active.polygon];if(remove)points.splice(index,1);else {const a=points[index],b=points[(index+1)%points.length];points.splice(index+1,0,[(a[0]+b[0])/2,(a[1]+b[1])/2]);}try{const room=withPolygon(active,points);change(d=>({...d,nodes:d.nodes.map(n=>n.id===active.id?room:n)}));}catch(e){setMessage(e.message);}};
  const active=doc.nodes.find(n=>n.id===selected), label=id=>doc.nodes.find(n=>n.id===id)?.label||id;
  return <main className="manual"><header><div><p className="eyebrow">CubiCasa · 25-plan benchmark</p><h1>Build your room graph</h1><p className="muted">Trace each room’s outline; its box is calculated automatically. Connect rooms using visible evidence.</p></div><div className="manual-actions"><a href="?mode=review">SVG reviewer ↗</a><button disabled={diskStatus==='Saving to cubicasa_eval…'} onClick={()=>{if(doc.image&&!confirm('Start a new plan? Confirm the folder save status or download your JSON first.'))return;replace(blank());setMessage('Choose your next image.');}}>New plan</button><button className="primary" disabled={!doc.image||outline!==null} onClick={save}>Download JSON</button></div></header>
  <section className="uploads"><label>Floor-plan image<input ref={fileRef} type="file" accept="image/png,image/jpeg" onChange={e=>{loadImage(e.target.files[0]);e.target.value='';}}/></label><label>Reopen saved JSON<input type="file" accept=".json" onChange={async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{const d=validate(JSON.parse(await f.text()));if(doc.image&&!confirm('Replace current annotation? Download its JSON first.'))return;replace(d);setMessage('Annotation restored. Select its original image to continue.');}catch(err){setMessage(err.message);}}}/></label><button disabled={!cache} onClick={()=>{try{const d=validate(JSON.parse(localStorage.getItem('fyp-manual-draft-v1')));replace(d);setMessage('Browser draft restored. Select its original image.');}catch(e){setMessage(e.message);}}}>Restore browser draft</button></section>
  <div className="manual-meta"><label>Unique plan ID<input value={doc.plan_id} placeholder="high_quality/1234" onChange={e=>setDoc({...doc,plan_id:e.target.value,status:'draft'})}/></label><label>Annotator<input value={doc.reviewer} placeholder="Your name or ID" onChange={e=>setDoc({...doc,reviewer:e.target.value,status:'draft'})}/></label><span>{doc.nodes.length} rooms · {doc.edges.length} edges · {doc.status}</span></div>
  <p role="status" className="manual-status">{message||'Images and completed graph edits save in cubicasa_eval after upload. Download JSON is also available as a backup.'}</p>
  <p role="status" className="manual-status">{diskStatus} {outline!==null&&'Finish the outline to save its corners.'}</p>
  <div className="manual-tools"><button disabled={!image||outline!==null} onClick={()=>startOutline(null)}>＋ Draw room outline</button>{[['add','＋ Place nodes'],['move','↔ Move / select'],['connect','↗ Connect nodes']].map(([id,title])=><button key={id} disabled={outline!==null} aria-pressed={mode===id} onClick={()=>{setMode(id);setPending(null);}}>{title}</button>)}<label>Room type <select value={kind} onChange={e=>setKind(e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Relation <select value={relation} onChange={e=>setRelation(e.target.value)}>{Object.entries(RELATIONS).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><button disabled={!history.length||outline!==null} onClick={()=>{setDoc(history.at(-1));setHistory(h=>h.slice(0,-1));setSelected(null);setPending(null);}}>Undo</button><label>Zoom <input type="range" min="1" max="3" step=".1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label><input type="checkbox" checked={showBoxes} onChange={e=>setShowBoxes(e.target.checked)}/> Show derived boxes</label></div>
  {outline!==null&&<div className="outline-tools"><b>{outlineTarget?`Outline for ${label(outlineTarget)}`:"New room outline"} · {outline.length} corners</b><button disabled={outline.length<3} onClick={finishOutline}>Finish outline</button><button disabled={!outline.length} onClick={()=>setOutline(p=>p.slice(0,-1))}>Undo corner</button><button onClick={cancelOutline}>Cancel outline</button><span>Click corners in order. Concave shapes are supported. Finish before saving.</span></div>}
  <p className="help">{mode==='outline'?'Click around the inside boundary of the room; do not repeat the first corner.':mode==='connect'?(pending?`Now select the room connected to ${label(pending)}.`:'Click two nodes to add a relation. Choosing another relation replaces the existing one.') :mode==='move'?'Drag a node within its room or drag the selected outline’s white corner handles.':'Click inside a room to add a node, then select it and choose Draw outline for selected room.'}</p>
  <section className="workspace manual-workspace"><div className="manual-canvas">{image&&doc.image?<svg ref={svg} aria-label="Floor-plan graph canvas" viewBox={`0 0 ${doc.image.width} ${doc.image.height}`} style={{width:`${zoom*100}%`,touchAction:'none'}} onPointerDown={e=>{if(e.target!==e.currentTarget)return;if(mode==='outline'){const p=point(e);setOutline(points=>[...points,[p.x,p.y]]);return;}if(mode!=='add')return;const p=point(e),id=crypto.randomUUID();change(d=>({...d,nodes:[...d.nodes,{id,type:kind,label:`${kind} ${d.nodes.filter(n=>n.type===kind).length+1}`,...p}]}));setSelected(id);}}
    onPointerMove={e=>{if(!drag.current)return;const p=point(e),action=drag.current;setDoc(d=>({...d,status:'draft',all_pairs_reviewed:false,nodes:d.nodes.map(n=>{if(n.id!==action.id)return n;if(action.vertex===undefined)return !n.polygon||contains(n.polygon,[p.x,p.y])?{...n,...p}:n;const points=n.polygon.map((v,i)=>i===action.vertex?[p.x,p.y]:v);return polygonError(points)?n:withPolygon(n,points);})}));}}
    onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
    <image href={image} width={doc.image.width} height={doc.image.height} style={{pointerEvents:'none'}}/>
    {doc.nodes.filter(n=>n.polygon).map(n=>{const [x0,y0,x1,y1]=n.bbox_xyxy;return <g key={`shape-${n.id}`} style={{pointerEvents:'none'}}><polygon points={n.polygon.map(p=>`${p[0]*doc.image.width},${p[1]*doc.image.height}`).join(' ')} fill={n.id===selected?'#f9731622':'#2563eb12'} stroke={n.id===selected?'#ea580c':'#2563eb'} strokeWidth="2" vectorEffect="non-scaling-stroke"/>{showBoxes&&<rect x={x0*doc.image.width} y={y0*doc.image.height} width={(x1-x0)*doc.image.width} height={(y1-y0)*doc.image.height} fill="none" stroke="#64748b" strokeDasharray="6 5" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/>}</g>;})}
    {outline!==null&&<g style={{pointerEvents:'none'}}><polyline points={outline.map(p=>`${p[0]*doc.image.width},${p[1]*doc.image.height}`).join(' ')} fill="#f59e0b22" stroke="#ea580c" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{outline.map((p,i)=><circle key={i} cx={p[0]*doc.image.width} cy={p[1]*doc.image.height} r={doc.image.width*.005} fill="#ea580c"/>)}</g>}
    {doc.edges.map(edge=>{const a=doc.nodes.find(n=>n.id===edge.a),b=doc.nodes.find(n=>n.id===edge.b);return <line key={pairKey(edge.a,edge.b)} x1={a.x*doc.image.width} y1={a.y*doc.image.height} x2={b.x*doc.image.width} y2={b.y*doc.image.height} stroke={COLOURS[edge.relation]} strokeWidth="3" vectorEffect="non-scaling-stroke" strokeDasharray={edge.relation==='adjacent_to'?'7 5':edge.relation==='uncertain'?'2 5':undefined} style={{pointerEvents:'none'}}/>;})}
    {doc.nodes.map(n=><g key={n.id} transform={`translate(${n.x*doc.image.width},${n.y*doc.image.height})`} onClick={e=>nodeClick(e,n)} onPointerDown={e=>{e.stopPropagation();if(mode!=='move')return;setSelected(n.id);setHistory(h=>[...h.slice(-49),doc]);drag.current={id:n.id};svg.current.setPointerCapture(e.pointerId);}} style={{pointerEvents:mode==='outline'?'none':'auto',cursor:mode==='move'?'grab':'pointer'}}><circle r={doc.image.width*.011} fill={pending===n.id?'#d97706':selected===n.id?'#ea580c':'#172554'} stroke="white" strokeWidth="2" vectorEffect="non-scaling-stroke"/><text y={-doc.image.width*.018} textAnchor="middle" fontSize={doc.image.width*.015} paintOrder="stroke" stroke="white" strokeWidth={doc.image.width*.004} fill="#172554">{n.label}</text></g>)}
    {mode==='move'&&active?.polygon?.map((p,i)=><circle key={`handle-${i}`} cx={p[0]*doc.image.width} cy={p[1]*doc.image.height} r={doc.image.width*.006} fill="white" stroke="#ea580c" strokeWidth="2" vectorEffect="non-scaling-stroke" style={{cursor:'grab'}} onPointerDown={e=>{e.stopPropagation();setHistory(h=>[...h.slice(-49),doc]);drag.current={id:active.id,vertex:i};svg.current.setPointerCapture(e.pointerId);}}><title>Corner {i+1}: drag to move</title></circle>)}
    </svg>:<div className="empty">{doc.image?'Select the original image to resume your saved graph.':'Upload a PNG or JPG to begin a blank graph.'}</div>}</div>
    <aside><h2>Rooms</h2><p className="help">{doc.nodes.filter(n=>n.polygon).length}/{doc.nodes.length} room outlines complete. Every room needs an outline before marking reviewed.</p><div className="manual-room-list">{doc.nodes.map(n=><button key={n.id} disabled={outline!==null} aria-pressed={selected===n.id} onClick={()=>{setSelected(n.id);setMode('move');setPending(null);}}>{n.label}</button>)}</div>{active&&<fieldset disabled={outline!==null} className="manual-editor"><label>Room label<input value={active.label} onChange={e=>change(d=>({...d,nodes:d.nodes.map(n=>n.id===selected?{...n,label:e.target.value}:n)}))}/></label><label>Room type<select value={active.type} onChange={e=>change(d=>({...d,nodes:d.nodes.map(n=>n.id===selected?{...n,type:e.target.value}:n)}))}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><button onClick={()=>{change(d=>({...d,nodes:d.nodes.filter(n=>n.id!==selected),edges:d.edges.filter(e=>e.a!==selected&&e.b!==selected)}));setSelected(null);setPending(null);}}>Delete room + its edges</button><button disabled={!image} onClick={()=>startOutline(active.id)}>{active.polygon?'Redraw outline':'Draw outline for selected room'}</button>{active.polygon?<><p className="help">{active.polygon.length} corners · box [x₀, y₀, x₁, y₁]: {active.bbox_xyxy.map(v=>v.toFixed(3)).join(', ')}. Box and outline use normalized image coordinates.</p><details><summary>Edit outline corners</summary>{active.polygon.map((p,i)=><div className="corner-row" key={i}><span>Corner {i+1}</span><button onClick={()=>editVertex(i)}>Insert after</button><button disabled={active.polygon.length<=3} onClick={()=>editVertex(i,true)}>Remove</button></div>)}</details><button onClick={()=>change(d=>({...d,nodes:d.nodes.map(n=>n.id===active.id?{...n,polygon:null,bbox_xyxy:null}:n)}))}>Remove outline, keep node</button></>:<p className="help">No outline yet. Add one to include this room in box-based evaluation.</p>}</fieldset>}
    <h2>Connections</h2><p className="help">Door and open passage mean direct access. Shared wall only means no direct access. Use uncertain when the image is unclear.</p><div className="manual-edges">{doc.edges.map(e=><div key={pairKey(e.a,e.b)}><span>{label(e.a)} ↔ {label(e.b)}</span><select aria-label={`Relation ${label(e.a)} to ${label(e.b)}`} value={e.relation} onChange={ev=>change(d=>({...d,edges:d.edges.map(x=>x===e?{...x,relation:ev.target.value}:x)}))}>{Object.entries(RELATIONS).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><button aria-label={`Delete edge ${label(e.a)} to ${label(e.b)}`} onClick={()=>change(d=>({...d,edges:d.edges.filter(x=>x!==e)}))}>Remove</button></div>)}</div>
    <label className="notes">Notes / ambiguities<textarea value={doc.notes} onChange={e=>setDoc({...doc,notes:e.target.value,status:'draft'})}/></label><label className="manual-check"><input type="checkbox" checked={doc.all_pairs_reviewed===true} onChange={e=>setDoc({...doc,all_pairs_reviewed:e.target.checked,status:'draft'})}/>I checked all room pairs. Unlisted pairs have no direct relation; ambiguous pairs are marked uncertain.</label><button className="primary" disabled={outline!==null||!image||!doc.nodes.length||!doc.plan_id.trim()||!doc.reviewer.trim()||!doc.all_pairs_reviewed||doc.nodes.some(n=>!n.label.trim()||!n.polygon)} onClick={()=>{setDoc({...doc,status:'manually_reviewed'});setMessage('Marked reviewed. Wait for the folder autosave confirmation.');}}>Mark reviewed</button></aside></section>
  </main>;
}
