from __future__ import annotations

import base64
import json
import shutil
import tempfile
from io import BytesIO
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st
from PIL import Image
import streamlit.components.v1 as components

from floorplan_app.core.registry import registry
from floorplan_app.core.models import SVGResult
from floorplan_app.pipeline.graph_extractor import extract_graph
from floorplan_app.pipeline.svg_extractor import extract_svg
import floorplan_app.parsers  # Registers built-in adapters.


PROJECT_ROOT = Path(__file__).resolve().parents[1]
INPUT_DIR = PROJECT_ROOT / 'input'
OUTPUT_DIR = Path(__file__).resolve().parent / 'outputs'
CUBIGRAPH_REPO = PROJECT_ROOT / 'third_party' / 'CubiGraph5K'
DEFAULT_IMAGE = INPUT_DIR / 'floor.jpg'  # Change this if you want another default.
# Bump this when a parser or SVG/graph conversion contract changes. It prevents
# Streamlit from showing a graph generated by an older pipeline implementation.
PIPELINE_REVISION = 'door-first-relations-v4'
ROOM_PALETTE = np.array([
    [105, 105, 105], [179, 222, 105], [255, 255, 179], [141, 211, 199],
    [253, 180, 98], [252, 205, 229], [128, 177, 211], [217, 217, 217],
    [251, 128, 114], [87, 122, 77], [255, 255, 255], [0, 0, 0],
], dtype=np.uint8)
ICON_PALETTE = np.array([
    [237, 230, 118], [141, 211, 199], [177, 89, 40], [253, 180, 98],
    [255, 255, 153], [252, 205, 229], [128, 177, 211], [217, 217, 217],
    [251, 128, 114], [105, 105, 105], [87, 122, 77],
], dtype=np.uint8)


def colourise(labels: np.ndarray, palette: np.ndarray) -> Image.Image:
    labels = np.asarray(labels, dtype=np.int64).clip(0, len(palette) - 1)
    return Image.fromarray(palette[labels])


def confidence_image(confidence: np.ndarray) -> Image.Image:
    return Image.fromarray(np.asarray(np.clip(confidence, 0, 1) * 255, dtype=np.uint8), mode='L')


def show_svg(svg_text: str, height: int = 650) -> None:
    components.html(svg_text, height=height, scrolling=True)


def overlay_graph_on_image(graph_svg: str, processed_image: Image.Image, *, image_opacity: float, image_on_top: bool) -> str:
    """Embed the parser canvas in graph SVG coordinates without rescaling either layer."""
    buffer = BytesIO()
    processed_image.save(buffer, format='PNG')
    encoded = base64.b64encode(buffer.getvalue()).decode('ascii')
    width, height = processed_image.size
    image_tag = (
        f'<image href="data:image/png;base64,{encoded}" x="0" y="0" '
        f'width="{width}" height="{height}" opacity="{image_opacity}" '
        'preserveAspectRatio="none" pointer-events="none" />'
    )
    if image_on_top:
        return graph_svg.replace('</svg>', image_tag + '</svg>')
    start = graph_svg.find('>') + 1
    return graph_svg[:start] + image_tag + graph_svg[start:]


def save_upload(uploaded) -> Path:
    suffix = Path(uploaded.name).suffix.lower() or '.png'
    target = Path(tempfile.mkdtemp(prefix='floorplan_upload_')) / f'input{suffix}'
    target.write_bytes(uploaded.getvalue())
    return target


@st.cache_data(show_spinner=False)
def run_pipeline(parser_name: str, image_bytes: bytes, image_suffix: str, max_side: int, threshold: float, pipeline_revision: str):
    temp_dir = Path(tempfile.mkdtemp(prefix='floorplan_run_'))
    try:
        image_path = temp_dir / f'input{image_suffix}'
        image_path.write_bytes(image_bytes)
        parser = registry.create(parser_name)
        parsed = parser.parse(image_path, max_side=max_side, postprocess_threshold=threshold)
        OUTPUT_DIR.mkdir(exist_ok=True)
        svg = extract_svg(parsed, OUTPUT_DIR / 'model.svg')
        graph = extract_graph(svg, CUBIGRAPH_REPO, OUTPUT_DIR / 'cubigraph_relations.svg')
        return parsed, svg, graph
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


@st.cache_data(show_spinner=False)
def run_svg_pipeline(svg_bytes: bytes, svg_label: str, pipeline_revision: str):
    """Run CubiGraph directly on an uploaded CubiGraph-compatible SVG."""
    svg_text = svg_bytes.decode('utf-8')
    if '<svg' not in svg_text.lower():
        raise ValueError('The uploaded file does not contain an SVG root element.')
    OUTPUT_DIR.mkdir(exist_ok=True)
    source_path = OUTPUT_DIR / 'uploaded_model.svg'
    source_path.write_text(svg_text, encoding='utf-8')
    svg_result = SVGResult(
        svg_text=svg_text,
        path=source_path,
        diagnostics={'source': 'uploaded SVG', 'filename': svg_label},
    )
    graph = extract_graph(svg_result, CUBIGRAPH_REPO, OUTPUT_DIR / 'uploaded_cubigraph_relations.svg')
    return svg_result, graph


st.set_page_config(page_title='Floorplan Pipeline Inspector', layout='wide')
st.title('Floorplan → SVG → Graph Inspector')
st.caption('Use this to locate whether an error began in image parsing, SVG conversion, or deterministic graph extraction.')

with st.sidebar:
    st.header('Pipeline controls')
    source_choice = st.radio('Pipeline input', ['Default image', 'Upload image', 'Upload SVG'])
    if source_choice != 'Upload SVG':
        parser_name = st.selectbox('Parser', registry.names(), help='New parsers appear here when registered in parsers/.')
        parser = registry.create(parser_name)
        st.caption(parser.description)
        max_side = st.slider('Maximum input side (px)', 512, 1600, 1024, step=128)
        threshold = st.slider('Structure post-processing threshold', 0.05, 0.60, 0.20, step=0.05)
        st.caption('Lower threshold finds more walls/openings but can introduce noise.')
    else:
        st.caption('Skip image parsing and run CubiGraph directly on an SVG.')
    if st.button('Clear cached pipeline result'):
        run_pipeline.clear()
        run_svg_pipeline.clear()
        st.session_state.pop('latest', None)
        st.experimental_rerun()

if source_choice == 'Upload SVG':
    uploaded_svg = st.file_uploader('Upload a CubiGraph-compatible SVG', type=['svg'])
    if uploaded_svg is None:
        st.info('Upload an SVG to run CubiGraph directly.')
        st.stop()
    svg_bytes, image_label = uploaded_svg.getvalue(), uploaded_svg.name
elif source_choice == 'Upload image':
    uploaded = st.file_uploader('Upload a floor-plan image', type=['png', 'jpg', 'jpeg'])
    if uploaded is None:
        st.info('Upload an image to run the pipeline.')
        st.stop()
    image_bytes, image_suffix, image_label = uploaded.getvalue(), Path(uploaded.name).suffix, uploaded.name
else:
    if not DEFAULT_IMAGE.exists():
        st.error(f'Default image not found: {DEFAULT_IMAGE}. Change DEFAULT_IMAGE in app.py or upload an image.')
        st.stop()
    image_bytes, image_suffix, image_label = DEFAULT_IMAGE.read_bytes(), DEFAULT_IMAGE.suffix, DEFAULT_IMAGE.name

if st.button('Run pipeline', type='primary'):
    with st.spinner('Running parser, SVG extraction, then CubiGraph…'):
        try:
            if source_choice == 'Upload SVG':
                svg_result, graph = run_svg_pipeline(svg_bytes, image_label, PIPELINE_REVISION)
                st.session_state['latest'] = {'mode': 'svg', 'svg': svg_result, 'graph': graph, 'label': image_label}
            else:
                parsed, svg_result, graph = run_pipeline(
                    parser_name, image_bytes, image_suffix, max_side, threshold, PIPELINE_REVISION
                )
                st.session_state['latest'] = {
                    'mode': 'image', 'parsed': parsed, 'svg': svg_result, 'graph': graph, 'label': image_label,
                }
        except Exception as error:
            st.exception(error)
            st.stop()

if 'latest' not in st.session_state:
    st.info('Select a parser and click **Run pipeline**.')
    st.stop()

latest = st.session_state['latest']
if latest['mode'] == 'svg':
    svg_result, graph, image_label = latest['svg'], latest['graph'], latest['label']
    st.success(f'Completed: {image_label} through CubiGraph (SVG-only mode)')
    metric_columns = st.columns(3)
    metric_columns[0].metric('Graph nodes', graph.diagnostics['nodes'])
    metric_columns[1].metric('Adjacency edges', graph.diagnostics['adjacent_edges'])
    metric_columns[2].metric('Door-connected edges', graph.diagnostics['door_connected_edges'])
    tab_svg, tab_graph, tab_diagnose = st.tabs(['1 · Input SVG', '2 · Graph', '3 · Diagnose'])
    with tab_svg:
        st.caption('Uploaded SVG passed directly to CubiGraph; no image parser was run.')
        show_svg(svg_result.svg_text)
        st.download_button('Download uploaded SVG', svg_result.svg_text, file_name='model.svg', mime='image/svg+xml')
    with tab_graph:
        st.caption('Door-first experimental policy: dashed edge = shared SVG Door; solid edge = adjacency only when no shared door is detected.')
        show_svg(graph.svg_text)
        st.json(graph.adjacency)
        st.download_button('Download graph SVG', graph.svg_text, file_name='cubigraph_relations.svg', mime='image/svg+xml')
        st.download_button('Download adjacency JSON', graph.diagnostics['adjacency_json'], file_name='cubigraph_adjacency.json', mime='application/json')
    with tab_diagnose:
        st.json({'svg': svg_result.diagnostics, 'graph': graph.diagnostics})
        st.caption('CubiGraph expects Space groups and optional Door Threshold groups. A valid XML SVG can still produce an incomplete graph if those semantic classes or polygons are missing.')
    st.stop()

parsed, svg_result, graph, image_label = latest['parsed'], latest['svg'], latest['graph'], latest['label']
st.success(f'Completed: {image_label} with {parsed.parser_name}')

metric_columns = st.columns(5)
metric_columns[0].metric('Room confidence', f"{parsed.diagnostics['room_pixel_confidence_mean']:.1%}")
metric_columns[1].metric('Low-tail confidence (p10)', f"{parsed.diagnostics['room_pixel_confidence_p10']:.1%}")
metric_columns[2].metric('SVG rooms', svg_result.diagnostics['rooms_exported'])
metric_columns[3].metric('SVG doors', svg_result.diagnostics['doors_exported'])
metric_columns[4].metric('Graph nodes / edges', f"{graph.diagnostics['nodes']} / {graph.diagnostics['adjacent_edges'] + graph.diagnostics['door_connected_edges']}")

tab_input, tab_parser, tab_svg, tab_graph, tab_diagnose = st.tabs([
    '1 · Input', '2 · Parser output', '3 · SVG bridge', '4 · Graph', '5 · Diagnose',
])

with tab_input:
    left, right = st.columns(2)
    left.image(parsed.source_image, caption=f'Original — {parsed.diagnostics["input_size"]}')
    right.image(parsed.processed_image, caption=f'Parser canvas — {parsed.diagnostics["processed_size"]}')

with tab_parser:
    left, middle, right = st.columns(3)
    left.image(colourise(parsed.room_segmentation, ROOM_PALETTE), caption='Post-processed rooms / walls')
    middle.image(colourise(parsed.icon_segmentation, ICON_PALETTE), caption='Post-processed icons')
    right.image(confidence_image(parsed.confidence_maps['room_best']), caption='Raw room-class confidence (white = confident)')
    st.caption('The coloured masks are post-processed geometry; the greyscale image is the model’s raw pixel-level confidence before polygon/graph conversion.')
    room_labels = np.argmax(parsed.room_segmentation if parsed.room_segmentation.ndim == 3 else np.zeros_like(parsed.room_segmentation), axis=0) if parsed.room_segmentation.ndim == 3 else parsed.room_segmentation
    rows = []
    for class_id, name in enumerate(parsed.room_class_names):
        mask = room_labels == class_id
        if mask.any():
            rows.append({'class': name, 'pixels': int(mask.sum()), 'share': f'{mask.mean():.1%}', 'mean raw confidence': f"{parsed.confidence_maps['room_best'][mask].mean():.1%}"})
    st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
    entities = []
    for geometry, metadata in zip(parsed.room_polygons, parsed.room_metadata):
        score = metadata.get('mean_class_confidence')
        entities.append({
            'stage': 'graph-candidate room', 'class': parsed.room_class_names[metadata['class']],
            'area (px²)': round(float(geometry.area), 1),
            'mean class confidence': f'{score:.1%}' if score is not None else 'unavailable',
        })
    for metadata in parsed.icon_metadata:
        if metadata.get('type') == 'icon':
            entities.append({
                'stage': 'icon', 'class': parsed.icon_class_names[metadata['class']],
                'area (px²)': '—', 'mean class confidence': metadata.get('prob', 'not exposed by parser'),
            })
    st.subheader('Extracted entities')
    st.dataframe(pd.DataFrame(entities), use_container_width=True, hide_index=True)
    st.caption('Room confidence = mean CubiCasa probability for the assigned semantic class inside that extracted polygon. It measures class support, not whether the polygon boundary or room identity is correct.')

with tab_svg:
    st.caption('This is an experimental pseudo-SVG reconstructed from parser polygons. Only Door predictions are exported as CubiGraph Thresholds; Windows are excluded.')
    show_svg(svg_result.svg_text)
    st.json(svg_result.diagnostics)
    st.download_button('Download generated model.svg', svg_result.svg_text, file_name='model.svg', mime='image/svg+xml')

with tab_graph:
    st.caption('Door-first experimental policy: dashed edge = shared predicted door; solid edge = adjacency only when no shared door is detected.')
    order = st.radio(
        'Overlay order', ['Graph over image', 'Image over graph'], horizontal=True,
        help='Both layers use the parser canvas, so room nodes and edges remain spatially aligned.',
    )
    image_opacity = st.slider('Original image opacity', 0.05, 1.00, 0.55, step=0.05)
    overlay = overlay_graph_on_image(
        graph.svg_text, parsed.processed_image, image_opacity=image_opacity,
        image_on_top=(order == 'Image over graph'),
    )
    show_svg(overlay)
    st.caption('The background is the original upload after the same resize/padding applied before CubiCasa inference. This keeps its coordinates aligned with the graph.')
    st.download_button('Download graph + aligned image overlay', overlay, file_name='graph_overlay.svg', mime='image/svg+xml')
    st.json(graph.adjacency)
    st.download_button('Download adjacency JSON', graph.diagnostics['adjacency_json'], file_name='cubigraph_adjacency.json', mime='application/json')

with tab_diagnose:
    flags = []
    if parsed.diagnostics['room_pixel_confidence_p10'] < 0.55:
        flags.append('Low-confidence room pixels: inspect the input’s line style, resolution, and labels.')
    if svg_result.diagnostics['undefined_rooms']:
        flags.append(f"{svg_result.diagnostics['undefined_rooms']} SVG room(s) are Undefined/Other: room class is uncertain before graph extraction.")
    if svg_result.diagnostics['doors_exported'] == 0:
        flags.append('No doors exported: dashed door-connect edges cannot be trusted or produced.')
    if graph.diagnostics['door_connected_edges']:
        flags.append('Dashed graph edges depend entirely on predicted door geometry; inspect them against the icon mask before treating them as facts.')
    if not flags:
        flags.append('No basic mismatch flags fired. Validate against a hand-annotated SVG before using this as ground truth.')
    st.subheader('Likely failure location')
    for flag in flags:
        st.warning(flag)
    st.subheader('Stage diagnostics')
    st.json({'parser': parsed.diagnostics, 'svg': svg_result.diagnostics, 'graph': graph.diagnostics})
    st.caption('To add DeepLabV3 later: make parsers/deeplabv3.py implement FloorplanParser, decorate it with @register_parser(...), and return ParserResult. The dashboard and downstream stages stay unchanged.')
